// Auto generated by nant generateGlue
// From a template at inc\template\src\ClientServerGlue\ClientGlue.cs
//
// Do not modify this file manually!
//
{#GPLFILEHEADER}

using System;
using System.Threading;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using Ict.Common;
using Ict.Common.Data;
using Ict.Common.Verification;
using Ict.Common.Remoting.Shared;
using Ict.Common.Remoting.Client;
using Ict.Petra.Shared;
{#USINGNAMESPACES}

namespace Ict.Petra.Client.App.Core.RemoteObjects
{
    /// the top level namespace for the module {#TOPLEVELMODULE}
    public class TM{#TOPLEVELMODULE}Namespace
    {
        {#SUBNAMESPACEPROPERTIES}
        {#SUBNAMESPACECLASSES}
    }
}

{##SUBNAMESPACEPROPERTY}
private T{#NAMESPACENAME}Namespace F{#NAMESPACENAME}Namespace = new T{#NAMESPACENAME}Namespace();

/// <summary>The '{#SUBNAMESPACENAME}' subnamespace contains further subnamespaces.</summary>
public T{#NAMESPACENAME}Namespace {#OBJECTNAME}
{
    get
    {
        return F{#NAMESPACENAME}Namespace;
    }
}

{##NAMESPACECLASS}
/// <summary> namespace definition </summary>
public class T{#NAMESPACENAME}Namespace
{
    {#CONNECTORMETHODS}
    {#SUBNAMESPACEPROPERTIES}
    {#SUBNAMESPACECLASSES}
}

{##WEBCONNECTORMETHODREMOTE}
/// forward the method call
public {#RETURNTYPE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    SortedList<string, object> ActualParameters = new SortedList<string, object>();
    {#ADDACTUALPARAMETERS}
    {#RESULT}THttpConnector.CallWebConnector("M{#TOPLEVELMODULE}", "{#WEBCONNECTORCLASS}.{#UNIQUEMETHODNAME}", ActualParameters, "{#EXPECTEDRETURNTYPE}");
    {#ASSIGNRESULTANDRETURN}
}

{##WEBCONNECTORMETHODSTANDALONE}
/// forward the method call
public {#RETURNTYPE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    // TODO: check permissions
    {#RETURN}{#WEBCONNECTORCLASS}.{#METHODNAME}({#ACTUALPARAMETERS});
}

{##UICONNECTORMETHODREMOTE}
/// create an object on the server side
public {#UICONNECTORINTERFACE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    return new {#UICONNECTORCLASSNAME}({#ACTUALPARAMETERS});
}

{#UICONNECTORCLASS}

{##UICONNECTORCLASS}
/// the implementation of the UIConnector for the client
public class {#UICONNECTORCLASSNAME}: {#UICONNECTORINTERFACE}, IDisposable
{
    private string FObjectID = String.Empty;

    {#CONSTRUCTORS}

    /// desctructor
    ~{#UICONNECTORCLASSNAME}()
    {
        Dispose();
    }

    /// dispose the object on the server as well
    public void Dispose()
    {
        THttpConnector.DisconnectUIConnector("M{#TOPLEVELMODULE}", FObjectID);
    }

    {#METHODSANDPROPERTIES}
}

{##UICONNECTORCONSTRUCTOR}
/// constructor, create the object on the server
public {#UICONNECTORCLASSNAME}({#PARAMETERDEFINITION})
{
    SortedList<string, object> ActualParameters = new SortedList<string, object>();
    {#ADDACTUALPARAMETERS}
    FObjectID = THttpConnector.CreateUIConnector("M{#TOPLEVELMODULE}", "{#METHODNAME}", ActualParameters);
}

{##UICONNECTORMETHOD}
/// access the UIConnector Method
public {#RETURNTYPE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    SortedList<string, object> ActualParameters = new SortedList<string, object>();
    {#ADDACTUALPARAMETERS}
    {#RESULT}THttpConnector.CallUIConnectorMethod(FObjectID, "M{#TOPLEVELMODULE}", "{#UICONNECTORCLASSNAME}", "{#UNIQUEMETHODNAME}", ActualParameters, "{#EXPECTEDRETURNTYPE}");
    {#ASSIGNRESULTANDRETURN}
}

{##UICONNECTORPROPERTY}
/// access the UIConnector Property
public {#TYPE} {#NAME}
{
{#IFDEF GETTER}
    get
    {
        {#GETTER}
    }
{#ENDIF GETTER}
{#IFDEF SETTER}
    set
    {
        THttpConnector.WriteUIConnectorProperty(FObjectID, "M{#TOPLEVELMODULE}", "{#UICONNECTORCLASSNAME}", "{#NAME}", value);
    }
{#ENDIF SETTER}
}

{##UICONNECTORMETHODSTANDALONE}
/// forward the method call
public {#UICONNECTORINTERFACE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    // TODO: check permissions
    return new {#UICONNECTORCLASS}({#ACTUALPARAMETERS});
}