// Auto generated by nant generateGlue
// From a template at inc\template\src\ClientServerGlue\ClientGlue.cs
//
// Do not modify this file manually!
//
{#GPLFILEHEADER}

using System;
using System.Threading;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using Ict.Common;
using Ict.Common.Data;
using Ict.Common.Verification;
using Ict.Petra.Shared;
{#USINGNAMESPACES}

namespace Ict.Petra.Client.App.Core.RemoteObjects
{
    /// the top level namespace for the module {#TOPLEVELMODULE}
    public class TM{#TOPLEVELMODULE}Namespace
    {
        {#SUBNAMESPACEPROPERTIES}
        {#SUBNAMESPACECLASSES}
    }
}

{##SUBNAMESPACEPROPERTY}
private T{#NAMESPACENAME}Namespace F{#NAMESPACENAME}Namespace = new T{#NAMESPACENAME}Namespace();

/// <summary>The '{#SUBNAMESPACENAME}' subnamespace contains further subnamespaces.</summary>
public T{#NAMESPACENAME}Namespace {#OBJECTNAME}
{
    get
    {
        return F{#NAMESPACENAME}Namespace;
    }
}

{##NAMESPACECLASS}
/// <summary> namespace definition </summary>
public class T{#NAMESPACENAME}Namespace
{
    {#CONNECTORMETHODS}
    {#SUBNAMESPACEPROPERTIES}
    {#SUBNAMESPACECLASSES}
}

{##WEBCONNECTORMETHODREMOTE}
/// forward the method call
public {#RETURNTYPE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    // TODO call through https interface {#RETURN}{#WEBCONNECTORCLASS}.{#METHODNAME}({#ACTUALPARAMETERS});
}

{##WEBCONNECTORMETHODSTANDALONE}
/// forward the method call
public {#RETURNTYPE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    {#RETURN}{#WEBCONNECTORCLASS}.{#METHODNAME}({#ACTUALPARAMETERS});
}

{##UICONNECTORMETHODREMOTE}
/// forward the method call
public {#UICONNECTORINTERFACE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    return ({#UICONNECTORINTERFACE}) TCreateRemotableObject.CreateRemotableObject(
            typeof({#UICONNECTORINTERFACE}),
            typeof({#UICONNECTORCLIENTREMOTINGCLASS}),
            new {#UICONNECTORCLASS}({#ACTUALPARAMETERS}));
}

{##UICONNECTORMETHODSTANDALONE}
/// forward the method call
public {#UICONNECTORINTERFACE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    return new {#UICONNECTORCLASS}({#ACTUALPARAMETERS});
}