export OpenPetraOrgPath=/usr/local/openpetraorg/${OrgNameWithoutSpace}
export CustomerName="${OrgName}"
export userName=openpetra${OrgNameWithoutSpace}
export OPENPETRA_RDBMSType=postgresql
export OPENPETRA_DBHOST=localhost
export OPENPETRA_DBPWD=${RandomDBPassword}
export OPENPETRA_DBUSER=petraserver_${OrgNameWithoutSpace}
export OPENPETRA_DBNAME=openpetra_${OrgNameWithoutSpace}
export OPENPETRA_DBPORT=5432
export OPENPETRA_PORT=${HostedPort}
export backupfile=$OpenPetraOrgPath/backup30/backup-`date +%Y%m%d`.sql.gz
export mono_path=/opt/mono-openpetra
export FASTCGI_MONO_SERVER=$mono_path/bin/fastcgi-mono-server4
export mono=$mono_path/bin/mono
